//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gladkov_Kursovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тех карты.
    /// </summary>
    // *** Start programmer edit section *** (ТехКарты CustomAttributes)

    // *** End programmer edit section *** (ТехКарты CustomAttributes)
    [AutoAltered()]
    [Caption("Тех карты")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТехКартыE", new string[] {
            "НомерКарты as \'Номер карты\'",
            "Дата as \'Дата\'"})]
    [AssociatedDetailViewAttribute("ТехКартыE", "ТчТехКарты", "ТчТехКартыE", true, "", "Тч тех карты", true, new string[] {
            ""})]
    [View("ТехКартыL", new string[] {
            "НомерКарты as \'Номер карты\'",
            "Дата as \'Дата\'"})]
    public class ТехКарты : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерКарты;
        
        private System.DateTime fДата;
        
        private IIS.Gladkov_Kursovaya.DetailArrayOfТчТехКарты fТчТехКарты;
        
        // *** Start programmer edit section *** (ТехКарты CustomMembers)

        // *** End programmer edit section *** (ТехКарты CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ТехКарты.Дата CustomAttributes)

        // *** End programmer edit section *** (ТехКарты.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ТехКарты.Дата Get start)

                // *** End programmer edit section *** (ТехКарты.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ТехКарты.Дата Get end)

                // *** End programmer edit section *** (ТехКарты.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТехКарты.Дата Set start)

                // *** End programmer edit section *** (ТехКарты.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ТехКарты.Дата Set end)

                // *** End programmer edit section *** (ТехКарты.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерКарты.
        /// </summary>
        // *** Start programmer edit section *** (ТехКарты.НомерКарты CustomAttributes)

        // *** End programmer edit section *** (ТехКарты.НомерКарты CustomAttributes)
        public virtual int НомерКарты
        {
            get
            {
                // *** Start programmer edit section *** (ТехКарты.НомерКарты Get start)

                // *** End programmer edit section *** (ТехКарты.НомерКарты Get start)
                int result = this.fНомерКарты;
                // *** Start programmer edit section *** (ТехКарты.НомерКарты Get end)

                // *** End programmer edit section *** (ТехКарты.НомерКарты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТехКарты.НомерКарты Set start)

                // *** End programmer edit section *** (ТехКарты.НомерКарты Set start)
                this.fНомерКарты = value;
                // *** Start programmer edit section *** (ТехКарты.НомерКарты Set end)

                // *** End programmer edit section *** (ТехКарты.НомерКарты Set end)
            }
        }
        
        /// <summary>
        /// Тех карты.
        /// </summary>
        // *** Start programmer edit section *** (ТехКарты.ТчТехКарты CustomAttributes)

        // *** End programmer edit section *** (ТехКарты.ТчТехКарты CustomAttributes)
        public virtual IIS.Gladkov_Kursovaya.DetailArrayOfТчТехКарты ТчТехКарты
        {
            get
            {
                // *** Start programmer edit section *** (ТехКарты.ТчТехКарты Get start)

                // *** End programmer edit section *** (ТехКарты.ТчТехКарты Get start)
                if ((this.fТчТехКарты == null))
                {
                    this.fТчТехКарты = new IIS.Gladkov_Kursovaya.DetailArrayOfТчТехКарты(this);
                }
                IIS.Gladkov_Kursovaya.DetailArrayOfТчТехКарты result = this.fТчТехКарты;
                // *** Start programmer edit section *** (ТехКарты.ТчТехКарты Get end)

                // *** End programmer edit section *** (ТехКарты.ТчТехКарты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТехКарты.ТчТехКарты Set start)

                // *** End programmer edit section *** (ТехКарты.ТчТехКарты Set start)
                this.fТчТехКарты = value;
                // *** Start programmer edit section *** (ТехКарты.ТчТехКарты Set end)

                // *** End programmer edit section *** (ТехКарты.ТчТехКарты Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТехКартыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТехКартыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТехКартыE", typeof(IIS.Gladkov_Kursovaya.ТехКарты));
                }
            }
            
            /// <summary>
            /// "ТехКартыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТехКартыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТехКартыL", typeof(IIS.Gladkov_Kursovaya.ТехКарты));
                }
            }
        }
    }
}
