//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gladkov_Kursovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч тех карты.
    /// </summary>
    // *** Start programmer edit section *** (ТчТехКарты CustomAttributes)

    // *** End programmer edit section *** (ТчТехКарты CustomAttributes)
    [AutoAltered()]
    [Caption("Тч тех карты")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТчТехКартыE", new string[] {
            "Заявки as \'Заявки\'",
            "Заявки.НаименДетали as \'Наимен детали\'",
            "Чертежи as \'Чертежи\'",
            "Чертежи.НомерЧертежа as \'Номер чертежа\'",
            "Заявки.Материалы.Наименование as \'Материал\'",
            "Оборудование as \'Оборудование\'",
            "Оборудование.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Заявки.НаименДетали",
            "Чертежи.НомерЧертежа",
            "Оборудование.Наименование"})]
    [MasterViewDefineAttribute("ТчТехКартыE", "Заявки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НаименДетали")]
    [MasterViewDefineAttribute("ТчТехКартыE", "Чертежи", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерЧертежа")]
    [MasterViewDefineAttribute("ТчТехКартыE", "Оборудование", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ТчТехКарты : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Gladkov_Kursovaya.Оборудование fОборудование;
        
        private IIS.Gladkov_Kursovaya.Заявки fЗаявки;
        
        private IIS.Gladkov_Kursovaya.Чертежи fЧертежи;
        
        private IIS.Gladkov_Kursovaya.ТехКарты fТехКарты;
        
        // *** Start programmer edit section *** (ТчТехКарты CustomMembers)

        // *** End programmer edit section *** (ТчТехКарты CustomMembers)

        
        /// <summary>
        /// Тч тех карты.
        /// </summary>
        // *** Start programmer edit section *** (ТчТехКарты.Заявки CustomAttributes)

        // *** End programmer edit section *** (ТчТехКарты.Заявки CustomAttributes)
        [PropertyStorage(new string[] {
                "Заявки"})]
        [NotNull()]
        public virtual IIS.Gladkov_Kursovaya.Заявки Заявки
        {
            get
            {
                // *** Start programmer edit section *** (ТчТехКарты.Заявки Get start)

                // *** End programmer edit section *** (ТчТехКарты.Заявки Get start)
                IIS.Gladkov_Kursovaya.Заявки result = this.fЗаявки;
                // *** Start programmer edit section *** (ТчТехКарты.Заявки Get end)

                // *** End programmer edit section *** (ТчТехКарты.Заявки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчТехКарты.Заявки Set start)

                // *** End programmer edit section *** (ТчТехКарты.Заявки Set start)
                this.fЗаявки = value;
                // *** Start programmer edit section *** (ТчТехКарты.Заявки Set end)

                // *** End programmer edit section *** (ТчТехКарты.Заявки Set end)
            }
        }
        
        /// <summary>
        /// Тч тех карты.
        /// </summary>
        // *** Start programmer edit section *** (ТчТехКарты.Оборудование CustomAttributes)

        // *** End programmer edit section *** (ТчТехКарты.Оборудование CustomAttributes)
        [PropertyStorage(new string[] {
                "Оборудование"})]
        [NotNull()]
        public virtual IIS.Gladkov_Kursovaya.Оборудование Оборудование
        {
            get
            {
                // *** Start programmer edit section *** (ТчТехКарты.Оборудование Get start)

                // *** End programmer edit section *** (ТчТехКарты.Оборудование Get start)
                IIS.Gladkov_Kursovaya.Оборудование result = this.fОборудование;
                // *** Start programmer edit section *** (ТчТехКарты.Оборудование Get end)

                // *** End programmer edit section *** (ТчТехКарты.Оборудование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчТехКарты.Оборудование Set start)

                // *** End programmer edit section *** (ТчТехКарты.Оборудование Set start)
                this.fОборудование = value;
                // *** Start programmer edit section *** (ТчТехКарты.Оборудование Set end)

                // *** End programmer edit section *** (ТчТехКарты.Оборудование Set end)
            }
        }
        
        /// <summary>
        /// Тч тех карты.
        /// </summary>
        // *** Start programmer edit section *** (ТчТехКарты.Чертежи CustomAttributes)

        // *** End programmer edit section *** (ТчТехКарты.Чертежи CustomAttributes)
        [PropertyStorage(new string[] {
                "Чертежи"})]
        [NotNull()]
        public virtual IIS.Gladkov_Kursovaya.Чертежи Чертежи
        {
            get
            {
                // *** Start programmer edit section *** (ТчТехКарты.Чертежи Get start)

                // *** End programmer edit section *** (ТчТехКарты.Чертежи Get start)
                IIS.Gladkov_Kursovaya.Чертежи result = this.fЧертежи;
                // *** Start programmer edit section *** (ТчТехКарты.Чертежи Get end)

                // *** End programmer edit section *** (ТчТехКарты.Чертежи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчТехКарты.Чертежи Set start)

                // *** End programmer edit section *** (ТчТехКарты.Чертежи Set start)
                this.fЧертежи = value;
                // *** Start programmer edit section *** (ТчТехКарты.Чертежи Set end)

                // *** End programmer edit section *** (ТчТехКарты.Чертежи Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Gladkov_Kursovaya.ТехКарты.
        /// </summary>
        // *** Start programmer edit section *** (ТчТехКарты.ТехКарты CustomAttributes)

        // *** End programmer edit section *** (ТчТехКарты.ТехКарты CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ТехКарты"})]
        public virtual IIS.Gladkov_Kursovaya.ТехКарты ТехКарты
        {
            get
            {
                // *** Start programmer edit section *** (ТчТехКарты.ТехКарты Get start)

                // *** End programmer edit section *** (ТчТехКарты.ТехКарты Get start)
                IIS.Gladkov_Kursovaya.ТехКарты result = this.fТехКарты;
                // *** Start programmer edit section *** (ТчТехКарты.ТехКарты Get end)

                // *** End programmer edit section *** (ТчТехКарты.ТехКарты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчТехКарты.ТехКарты Set start)

                // *** End programmer edit section *** (ТчТехКарты.ТехКарты Set start)
                this.fТехКарты = value;
                // *** Start programmer edit section *** (ТчТехКарты.ТехКарты Set end)

                // *** End programmer edit section *** (ТчТехКарты.ТехКарты Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТчТехКартыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТчТехКартыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТчТехКартыE", typeof(IIS.Gladkov_Kursovaya.ТчТехКарты));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТчТехКарты.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТчТехКарты CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТчТехКарты CustomAttributes)
    public class DetailArrayOfТчТехКарты : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Gladkov_Kursovaya.DetailArrayOfТчТехКарты members)

        // *** End programmer edit section *** (IIS.Gladkov_Kursovaya.DetailArrayOfТчТехКарты members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТчТехКарты by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТчТехКарты.
        /// </summary>
        public DetailArrayOfТчТехКарты(IIS.Gladkov_Kursovaya.ТехКарты fТехКарты) : 
                base(typeof(ТчТехКарты), ((ICSSoft.STORMNET.DataObject)(fТехКарты)))
        {
        }
        
        public IIS.Gladkov_Kursovaya.ТчТехКарты this[int index]
        {
            get
            {
                return ((IIS.Gladkov_Kursovaya.ТчТехКарты)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Gladkov_Kursovaya.ТчТехКарты dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
