//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gladkov_Kursovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Чертежи.
    /// </summary>
    // *** Start programmer edit section *** (Чертежи CustomAttributes)

    // *** End programmer edit section *** (Чертежи CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЧертежиE", new string[] {
            "НомерЧертежа as \'Номер чертежа\'",
            "ДатаСоздания as \'Дата создания\'",
            "Заявки as \'Заявки\'",
            "Заявки.НаименДетали as \'Деталь\'",
            "Заявки.Материалы.Наименование as \'Материал\'",
            "Утверждение as \'Утверждение\'"}, Hidden=new string[] {
            "Заявки.НаименДетали"})]
    [MasterViewDefineAttribute("ЧертежиE", "Заявки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НаименДетали")]
    [View("ЧертежиL", new string[] {
            "НомерЧертежа as \'Номер чертежа\'",
            "ДатаСоздания as \'Дата создания\'",
            "Заявки.НаименДетали as \'Деталь\'",
            "Заявки.Материалы as \'материал\'",
            "Заявки.Материалы.Наименование as \'Материал\'",
            "Утверждение as \'Утверждение\'"})]
    public class Чертежи : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЧертежа;
        
        private System.DateTime fДатаСоздания;
        
        private bool fУтверждение;
        
        private IIS.Gladkov_Kursovaya.Заявки fЗаявки;
        
        // *** Start programmer edit section *** (Чертежи CustomMembers)

        // *** End programmer edit section *** (Чертежи CustomMembers)

        
        /// <summary>
        /// ДатаСоздания.
        /// </summary>
        // *** Start programmer edit section *** (Чертежи.ДатаСоздания CustomAttributes)

        // *** End programmer edit section *** (Чертежи.ДатаСоздания CustomAttributes)
        public virtual System.DateTime ДатаСоздания
        {
            get
            {
                // *** Start programmer edit section *** (Чертежи.ДатаСоздания Get start)

                // *** End programmer edit section *** (Чертежи.ДатаСоздания Get start)
                System.DateTime result = this.fДатаСоздания;
                // *** Start programmer edit section *** (Чертежи.ДатаСоздания Get end)

                // *** End programmer edit section *** (Чертежи.ДатаСоздания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чертежи.ДатаСоздания Set start)

                // *** End programmer edit section *** (Чертежи.ДатаСоздания Set start)
                this.fДатаСоздания = value;
                // *** Start programmer edit section *** (Чертежи.ДатаСоздания Set end)

                // *** End programmer edit section *** (Чертежи.ДатаСоздания Set end)
            }
        }
        
        /// <summary>
        /// НомерЧертежа.
        /// </summary>
        // *** Start programmer edit section *** (Чертежи.НомерЧертежа CustomAttributes)

        // *** End programmer edit section *** (Чертежи.НомерЧертежа CustomAttributes)
        public virtual int НомерЧертежа
        {
            get
            {
                // *** Start programmer edit section *** (Чертежи.НомерЧертежа Get start)

                // *** End programmer edit section *** (Чертежи.НомерЧертежа Get start)
                int result = this.fНомерЧертежа;
                // *** Start programmer edit section *** (Чертежи.НомерЧертежа Get end)

                // *** End programmer edit section *** (Чертежи.НомерЧертежа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чертежи.НомерЧертежа Set start)

                // *** End programmer edit section *** (Чертежи.НомерЧертежа Set start)
                this.fНомерЧертежа = value;
                // *** Start programmer edit section *** (Чертежи.НомерЧертежа Set end)

                // *** End programmer edit section *** (Чертежи.НомерЧертежа Set end)
            }
        }
        
        /// <summary>
        /// Утверждение.
        /// </summary>
        // *** Start programmer edit section *** (Чертежи.Утверждение CustomAttributes)

        // *** End programmer edit section *** (Чертежи.Утверждение CustomAttributes)
        public virtual bool Утверждение
        {
            get
            {
                // *** Start programmer edit section *** (Чертежи.Утверждение Get start)

                // *** End programmer edit section *** (Чертежи.Утверждение Get start)
                bool result = this.fУтверждение;
                // *** Start programmer edit section *** (Чертежи.Утверждение Get end)

                // *** End programmer edit section *** (Чертежи.Утверждение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чертежи.Утверждение Set start)

                // *** End programmer edit section *** (Чертежи.Утверждение Set start)
                this.fУтверждение = value;
                // *** Start programmer edit section *** (Чертежи.Утверждение Set end)

                // *** End programmer edit section *** (Чертежи.Утверждение Set end)
            }
        }
        
        /// <summary>
        /// Чертежи.
        /// </summary>
        // *** Start programmer edit section *** (Чертежи.Заявки CustomAttributes)

        // *** End programmer edit section *** (Чертежи.Заявки CustomAttributes)
        [PropertyStorage(new string[] {
                "Заявки"})]
        [NotNull()]
        public virtual IIS.Gladkov_Kursovaya.Заявки Заявки
        {
            get
            {
                // *** Start programmer edit section *** (Чертежи.Заявки Get start)

                // *** End programmer edit section *** (Чертежи.Заявки Get start)
                IIS.Gladkov_Kursovaya.Заявки result = this.fЗаявки;
                // *** Start programmer edit section *** (Чертежи.Заявки Get end)

                // *** End programmer edit section *** (Чертежи.Заявки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чертежи.Заявки Set start)

                // *** End programmer edit section *** (Чертежи.Заявки Set start)
                this.fЗаявки = value;
                // *** Start programmer edit section *** (Чертежи.Заявки Set end)

                // *** End programmer edit section *** (Чертежи.Заявки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЧертежиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧертежиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧертежиE", typeof(IIS.Gladkov_Kursovaya.Чертежи));
                }
            }
            
            /// <summary>
            /// "ЧертежиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧертежиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧертежиL", typeof(IIS.Gladkov_Kursovaya.Чертежи));
                }
            }
        }
    }
}
